name: macOS CI
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: macos-latest
    env:
      CXXFLAGS: -std=${{ matrix.standard }} -I/usr/local/opt/openssl@1.1/include -Wno-error=deprecated-declarations
      LDFLAGS: -L/usr/local/opt/openssl@1.1/lib
      PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig
      TEST_BUILD_MODULES: geo_maxmind ldap mysql pgsql regex_pcre regex_posix regex_re2 regex_stdlib regex_tre sqlite3 ssl_gnutls ssl_mbedtls ssl_openssl sslrehashsignal
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew update
          brew install pkg-config gnutls libmaxminddb libpq mbedtls mysql-client openssl@1.1 pcre re2 sqlite3 tre
          brew link --force libpq
          brew link --force mysql-client
      - name: Run test-build
        run: ./tools/test-build c++
    strategy:
      matrix:
        standard:
          - gnu++98
          - c++14
