name: misspell fixer
on:
  schedule:
    - cron: '0 0 15 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Whitelist some directories and files
      run: |
        echo "\
        ^./.github/workflows
        ^./.mailmap
        ^./vendor
        ^./make/directive.pm:287:atleast
        ^./src/modules/m_disable.cpp:119:existant
        ^./docs/conf/helpop.conf.example:443:ALLTIME
        ^./docs/conf/helpop.conf.example:551:ALLTIME
        ^./docs/conf/helpop.conf.example:551:alltime
        ^./docs/conf/modules.conf.example:170:Alltime
        ^./docs/conf/modules.conf.example:171:ALLTIME
        ^./docs/conf/modules.conf.example:172:ALLTIME
        ^./docs/conf/modules.conf.example:173:alltime
        ^./docs/conf/opers.conf.example:58:ALLTIME
        ^./src/modules/m_alltime.cpp:31:ALLTIME
        ^./src/modules/m_alltime.cpp:65:ALLTIME\
        " > ${{ runner.workspace }}/inspircd/.misspell-fixer.ignore
    - uses: sobolevn/misspell-fixer-action@master
      with:
        options: '-rvnfuRVD .'
    - uses: peter-evans/create-pull-request@v2.4.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        author: 'InspIRCd Robot <noreply@inspircd.org>'
        commiter: 'InspIRCd Robot <noreply@inspircd.org>'
        commit-message: 'Fixes by misspell-fixer'
        title: 'Typos fix by misspell-fixer'
        reviewers: 'genius3000'
